version: '3.4'

services:
  balones:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  uniformes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

